name: "JFrog Integration"
on: 
  push:
  pull_request:
  workflow_dispatch:
env:
  MajorVersion: '0'
  MinorVersion: '1'
  PrototypeAPIUrl: http://placeholder
  system_debug: 'false'
  
jobs:
  build:
     runs-on: windows-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.0
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: https://incloudmaster.jfrog.io
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
       - name: Setup Node npm
         uses: actions/setup-node@v4.0.0
         with:
           node-version: 20.3.1
           
       - name: Set CLI Config
         run: jf npm-config --global=true  --repo-resolve=ashritha-npm  --repo-deploy=ashritha-npm 
           
       - name: Install Deps
         run: jf npm install 
        
         
       - name: Build Project
         run: jf npm run

       - name: Pack and publish the npm package to Artifactory, while recording it as an artifact in the build-info
         run: jf npm publish 
         

       - name: Publish Build info With JFrog CLI
         run: |
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
